name: Run Cypress Tests

on: [push]

jobs:
  cypress-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
      - name: CI Setup
        run: |
          npm ci
          npx cypress verify
          npx cypress info
      - name: Execute Cypress tests
        run: npx cypress run
      - uses: actions/upload-artifact@v2
        with:
          name: tests-report
          path: cypress/tmp/reports
